name: Basic CI on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Kiểm tra cú pháp (ví dụ file Python)
        run: |
          echo "📁 List file:"
          ls -la
          echo "🧪 Kiểm tra file .py (nếu có)"
          find . -name "*.py" -exec python3 -m py_compile {} \; || echo "Không có file .py nào"
