name: Update Jira on Merge

on:
  pull_request:
    types: [closed]

jobs:
  update-jira:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Extract Jira Issue Key
        id: extract
        run: |
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "JIRA_KEY=$(echo ${{ github.event.pull_request.title }} | grep -oE '[A-Z]+-[0-9]+')" >> $GITHUB_ENV

      - name: Update Jira Issue
        run: |
          curl -X PUT \
            -u ${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
            -H "Content-Type: application/json" \
            --data '{"transition":{"id":"31"}}' \
            "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ env.JIRA_KEY }}/transitions"
